### PR TITLE
Update to rspec3 syntax

### PR DESCRIPTION
**Pull request by brianstien**
This switches to rspec3 syntax.  I think this will need a major version bump.

### CODE REVIEW

**Comment by liveh2o** [comment]
We should probably also update the gemspec to require RSpec 3 or higher, right?

**Comment by liveh2o** [comment]
Or at least the version that the new syntax showed up.

**Comment by brianstien** [comment]
After looking into it, this is supported since at least rspec 2.14 http://rspec.info/blog/2013/07/rspec-2-14-is-released/http://rspec.info/blog/2013/07/rspec-2-14-is-released/

I was wrong in thinking we might need a major version bump.  We do not need a major version bump or to change dependencies

**Comment by liveh2o** [comment]
I think the minimum is v2.8, so we do need to up that to v2.14+.

**Comment by brianstien** [comment]
2.8 > 2.1, we already depend on 2.8 or later, which is later than 2.14

**Comment by liveh2o** [comment]
It's not, actually. Ruby gems is smart enough to figure that out.

**Comment by liveh2o** [comment]
ezgif-3518449088

**Pull request merged**
